version: '3.8'

services:
  http-dotnet:
    image: demo-api
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:80"
    deploy:
      resources:
        limits:
          memory: 50m

  http-dotnet2:
    image: demo-api
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3001:80"
    deploy:
      resources:
        limits:
          memory: 50M

  http-dotnet3:
    image: demo-api
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3002:80"
    deploy:
      resources:
        limits:
          memory: 50M

  http-dotnet4:
    image: demo-api
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3003:80"
    deploy:
      resources:
        limits:
          memory: 50M

  http-dotnet5:
    image: demo-api
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3004:80"
    deploy:
      resources:
        limits:
          memory: 50M
        



