version: '3.8'

services:
  http-dotnet:
    build:
      context: ./
      dockerfile: Dockerfile
    environment: 
      - HOSTNAME=http-dotnet_http-dotnet_
      - SERVICES=5
    ports:
      - target: 80
    deploy:
      replicas: 5
      resources:
        limits:
          memory: 50m
        



