version: '3.8'

services:
  http-dotnet:
    build:
      context: ./
      dockerfile: Dockerfile
    environment: 
      - EmailServer=172.2.0.18
    ports:
      - target: 80
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 50m
        



